config/routes.rb
Spree::Core::Engine.add_routes do
  namespace :admin do
    resource :order_notification_settings, only: [:edit, :update]
  end
end

app/models/spree/order_decorator.rb
Spree::Order.class_eval do
  alias_method :super_deliver_order_confirmation_email, :deliver_order_confirmation_email


  # Modified to also send notification email
  def deliver_order_confirmation_email
    super_deliver_order_confirmation_email # Call Super

    # Send notficiation email
    setting = Spree::OrderNotificationSetting.new
    if setting[:mailer_complete_enabled]
      to_addresses = setting[:mailer_complete_to].delete(' ').split(',')
      from_address = setting[:mailer_complete_from]
      cc_addresses = setting[:mailer_complete_cc].delete(' ').split(',')
      bcc_addresses = setting[:mailer_complete_bcc].delete(' ').split(',')

      Spree::OrderNotificationMailer.order_complete_state_email(
        id,
        to_addresses,
        from_address,
        cc_addresses,
        bcc_addresses
      ).deliver_later
    end
  end

end

app/models/spree/order_notification_setting.rb
module Spree
  class OrderNotificationSetting < Preferences::Configuration
    preference :mailer_complete_enabled, :boolean,   default: false
    preference :mailer_complete_to,      :string,    default: ''
    preference :mailer_complete_cc,      :string,    default: ''
    preference :mailer_complete_bcc,     :string,    default: ''
    preference :mailer_complete_from,    :string,    default: ''
  end
end

app/controllers/spree/admin/order_notification_settings_controller.rb
module Spree
  module Admin
    class OrderNotificationSettingsController < ResourceController
      def update
        config = Spree::OrderNotificationSetting.new

        preferences = params && params.key?(:preferences) ? params.delete(:preferences) : params

        # Validations
        # TODO: Move to Model?
        if params[:mailer_complete_enabled] == "1"

          # Make sure 'To' has a value
          if params[:mailer_complete_to].delete(' ').split(',').count == 0
            update_error_redirect(Spree.t(:order_notification_error_mailer_to_value_required)) and return
          end

          # Make sure 'From' is valid email address
          if (params[:mailer_complete_from] =~ Devise::email_regexp).nil?
            update_error_redirect(Spree.t(:order_notification_error_mailer_from_invalid_email)) and return
          end

          # Ensure To, CC, BCC are valid
          {
            'order_notification_mailer_to': :mailer_complete_to,
            'order_notification_mailer_cc': :mailer_complete_cc,
            'order_notification_mailer_bcc': :mailer_complete_bcc
          }.each do |key, value|
            params[value].delete(' ').split(',').each do |email|
              if (email =~ Devise::email_regexp).nil?
                update_error_redirect(Spree.t(:order_notification_error_update_invalid_format, preference: Spree.t(key.to_sym))) and return
              end
            end
          end
        end

        preferences.each do |name, value|
          next unless config.has_preference? name
          config[name] = value
        end

        flash[:success] = Spree.t(:successfully_updated, resource: Spree.t(:order_notification))
        redirect_to edit_admin_order_notification_settings_path
      end

      private

        def update_error_redirect(message = "Error updating")
          flash[:error] = message
          redirect_to edit_admin_order_notification_settings_path
        end
    end
  end
end

app/views/spree/admin/order_notification_settings/edit.html.erb
<!-- Menu -->
<%= render :partial => 'spree/admin/shared/configuration_menu' %>


<!-- Meta -->
<% content_for :page_title do %>
  <%= Spree.t(:order_notification) %>
<% end %>


<!-- Form -->
<%= form_tag admin_order_notification_settings_path, method: :put do %>
  <fieldset class="general">

    <!-- Legend -->
    <legend align="center"><%= Spree.t(:order_complete_notification_mailer)%></legend>

    <!-- Enabled -->
    <div class="field">
      <%= label_tag(:mailer_complete_enabled) do %>
        <%= preference_field_tag(:mailer_complete_enabled, SpreeOrderNotification::Config[:mailer_complete_enabled], type: :boolean) %>
        <%= Spree.t(:enable_order_complete_notification_mailer) %>
      <% end %>
    </div><!-- /.field -->

    <!-- To -->
    <div class="field">
      <%= label_tag(:mailer_complete_to, Spree.t(:order_notification_mailer_to)) %>
      <br />
      <%= preference_field_tag(:mailer_complete_to, SpreeOrderNotification::Config[:mailer_complete_to], class: 'control-form') %>
      <br />
      <p class="help-block"><%= Spree.t(:order_notification_mailer_help) %></p>
    </div><!-- /.field -->

    <!-- CC -->
    <div class="field">
      <%= label_tag(:mailer_complete_cc, Spree.t(:order_notification_mailer_cc)) %>
      <br />
      <%= preference_field_tag(:mailer_complete_cc, SpreeOrderNotification::Config[:mailer_complete_cc], class: 'control-form') %>
      <br />
      <p class="help-block"><%= Spree.t(:order_notification_mailer_help) %></p>
    </div><!-- /.field -->

    <!-- BCC -->
    <div class="field">
      <%= label_tag(:mailer_complete_bcc, Spree.t(:order_notification_mailer_bcc)) %>
      <br />
      <%= preference_field_tag(:mailer_complete_bcc, SpreeOrderNotification::Config[:mailer_complete_bcc], class: 'control-form') %>
      <br />
      <p class="help-block"><%= Spree.t(:order_notification_mailer_help) %></p>
    </div><!-- /.field -->

    <!-- From -->
    <div class="field">
      <%= label_tag(:mailer_complete_from, Spree.t(:order_notification_mailer_from)) %>
      <br />
      <%= preference_field_tag(:mailer_complete_from, SpreeOrderNotification::Config[:mailer_complete_from], class: 'control-form') %>
    </div><!-- /.field -->

    <!-- Actions -->
    <div class="form-buttons filter-actions actions" data-hook="buttons">
      <%= button Spree.t('actions.update'), 'update' %>
    </div><!-- /.actions -->

  </fieldset><!-- /.general -->
<% end %>